### PR TITLE
chore: Update indirect dependency to knative.dev/serving v0.37.5

### PR DESCRIPTION
**Pull request by ckadner**
#### Motivation

Address https://github.com/kserve/modelmesh-serving/security/dependabot/11

#### Modifications

Override/replace indirect dependency to `knative.dev/serving v0.37.5`

- Which has fix https://github.com/knative/serving/pull/14523:
  See https://github.com/knative/serving/tree/v0.37.5/pkg/autoscaler/metrics

---

<details>

<summary><b>Problems with using `knative.dev/serving v0.39.0`</b></summary>

The Mitigation steps for the Security Vulnerability report suggest updating to `knative.dev/serving v0.39.0`.

However this forces an upgrade of several other direct/indirect dependencies causing incompatibilities:

-  with this upgrade, also `k8s.io/api` and `k8s.io/client-go` are upgraded to `v0.27.+`, but this causes compilation errors:
   ```
   # sigs.k8s.io/controller-runtime/pkg/cache
   /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/cache/multi_namespace_cache.go:308:9:
   cannot use handles (variable of type map[string]"k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration)
   as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement:
   map[string]"k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration
   does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSynced)
   ```
- now `controller-runtime` `v0.15.0` onward supports `HasSynced`: 
  - https://github.com/kubernetes-sigs/controller-runtime/pull/2223
- but we can't upgrade to `controller-runtime` `v0.15.0` without breaking the KServe (`0.11.2`) API integration
  ```
  could not import github.com/kserve/kserve/pkg/apis/serving/v1alpha1 (-: # github.com/kserve/kserve/pkg/apis/serving/v1alpha1
  /root/go/pkg/mod/github.com/kserve/kserve@v0.11.2/pkg/apis/serving/v1alpha1/inference_graph_validation.go:61:27: cannot use &InferenceGraph{} (value of type *InferenceGraph) as admission.Validator value in variable declaration: *InferenceGraph does not implement admission.Validator (wrong type for method ValidateCreate)
                  have ValidateCreate() error
                  want ValidateCreate() (admission.Warnings, error)
  /root/go/pkg/mod/github.com/kserve/kserve@v0.11.2/pkg/apis/serving/v1alpha1/trainedmodel_webhook.go:51:27: cannot use &TrainedModel{} (value of type *TrainedModel) as admission.Validator value in variable declaration: *TrainedModel does not implement admission.Validator (wrong type for method ValidateCreate)
                  have ValidateCreate() error
                  want ValidateCreate() (admission.Warnings, error)) (typecheck)
          "github.com/kserve/kserve/pkg/apis/serving/v1alpha1"
  ```
- so we need to pin "down" `k8s.io/api` and `k8s.io/client-go` below `v0.27.0` until https://github.com/kubernetes-sigs/controller-runtime/issues/2302 is addressed.
  ```
	k8s.io/api => k8s.io/api v0.26.4
	k8s.io/client-go => k8s.io/client-go v0.26.4
	k8s.io/code-generator => k8s.io/code-generator v0.26.4
  ```
- ~~that downgrade however would re-introduce another vulnerability we previously mitigated~~
  ```
	// Fixes github.com/elazarl/goproxy Denial of Service (DoS)
	// This dependency was removed from apimachinery 0.27.0
	// remove after upgrade to controller-runtime 0.15.x or apimachinery to 0.27.x
	k8s.io/apimachinery => k8s.io/apimachinery v0.27.0
  ```
- once we upgrade to KServe `v0.12.0` along with Go 1.21 we should be able to upgrade to `controller-runtime`
  to `v0.15.0` and things should get a bit less messy

</details>

---

@spolti

### CODE REVIEW

File: go.mod [hunk 1]
```diff
@@ -19,37 +19,37 @@ require (
...
-	google.golang.org/protobuf v1.30.0
-	k8s.io/api v0.26.4
-	k8s.io/apimachinery v0.26.4
-	k8s.io/client-go v0.26.4
-	knative.dev/pkg v0.0.0-20230502134655-db8a35330281
+	google.golang.org/grpc v1.58.3
+	google.golang.org/protobuf v1.31.0
+	k8s.io/api v0.27.6
+	k8s.io/apimachinery v0.27.6
+	k8s.io/client-go v0.27.6
```
Comment (spolti) [inline go.mod:29]: There is a similar issue than CI reported saying that the issue is fixed on 0.27.2, however the version here is 0.27.6:
https://github.com/operator-framework/operator-sdk/issues/6396
https://github.com/kubernetes-sigs/controller-runtime/issues/2302

might need to bump to 0.28.x instead.

File: go.mod [hunk 2]
```diff
@@ -139,4 +142,6 @@ replace (
 	// Fixes github.com/elazarl/goproxy Denial of Service (DoS)
 	// This dependency was removed from apimachinery 0.27.0
 	k8s.io/apimachinery => k8s.io/apimachinery v0.27.0
+	// Update knative/serving to avoid CVE-2023-48713
+	knative.dev/serving => knative.dev/serving v0.39.0
```
Comment (spolti) [inline go.mod:146]: Regarding the CVE-2023-48713 I seeing this report:
https://security.snyk.io/vuln/SNYK-GOLANG-KNATIVEDEVSERVINGPKGAUTOSCALERMETRICS-6091906

says 1.10.5 or 1.11.3 +

Comment (spolti) [reply go.mod:146]: actually, it seems that it should be 0.39.3:
https://github.com/opendatahub-io/kserve/pull/171

File: go.mod (hunk 1 above)
Comment (spolti) [reply go.mod:29]: For now pinning with 0.26.4 has fixed the problem.

```
	// pin to 0.26.4 to avoid https://github.com/kubernetes-sigs/controller-runtime/issues/2302
	k8s.io/api => k8s.io/api v0.26.4
	k8s.io/client-go => k8s.io/client-go v0.26.4
	k8s.io/code-generator => k8s.io/code-generator v0.26.4
```

File: go.mod (hunk 2 above)
Comment (ckadner) [reply go.mod]: The Dependabot alert says:

> Upgrade `knative.dev/serving` to version `0.39.0` or later

and ...

> The vulnerability has been patched in `v1.10.5`, `v1.11.3` and `v1.12.0`


However, the fix:
- https://github.com/knative/serving/pull/14523

... was back-ported to many more release streams, i.e. `v0.37.5` and `v0.38.3`:
- https://github.com/knative/serving/tree/v0.37.5/pkg/autoscaler/metrics
- https://github.com/knative/serving/tree/v0.38.3/pkg/autoscaler/metrics

File: go.mod (hunk 1 above)
Comment (ckadner) [reply go.mod:29]: Yup, sadly.

**Comment by ckadner** [comment]
Thanks @spolti -- took quite a bit of finagling to get this update to work. Should get easier once we moved to Go 1.21

File: go.mod [hunk 3]
```diff
@@ -85,59 +85,71 @@ require (
...
-	// before removing it make sure that the next version of the related k8s dependencies contains the fix
-	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp => go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.44.0
-	// Update Go Crypto to avoid CVE-2022-27191, CVE-2021-43565, CVE-2020-29652, CVE-2023-48795
-	golang.org/x/crypto => golang.org/x/crypto v0.17.0
-	// Update Go Networking to avoid CVE-2023-44487 and CVE-2023-39325
-	golang.org/x/net => golang.org/x/net v0.17.0
-	// remove when upgrade to controller-runtime 0.15.x or apimachinery to 0.27.x
-	// Fixes github.com/elazarl/goproxy Denial of Service (DoS)
-	// This dependency was removed from apimachinery 0.27.0
-	k8s.io/apimachinery => k8s.io/apimachinery v0.27.0
```
Comment (ckadner) [inline go.mod:142]: this one is a bit of a problem 🤔

Comment (ckadner) [reply go.mod:142]: I will give this one another shot

Comment (ckadner) [reply go.mod:142]: Seems to be fine after another `replace`ments

```
[modelmesh-serving] (update_knative_serving =)$  go mod graph | grep elazarl/goproxy

[modelmesh-serving] (update_knative_serving =)$  
```

File: go.mod [hunk 4]
```diff
@@ -85,59 +85,76 @@ require (
...
+replace go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp => go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.44.0
+
+// Update Go Crypto to avoid CVE-2022-27191, CVE-2021-43565, CVE-2020-29652, CVE-2023-48795
+replace golang.org/x/crypto => golang.org/x/crypto v0.17.0
+
+// Update Go Networking to avoid CVE-2023-44487 and CVE-2023-39325
+replace golang.org/x/net => golang.org/x/net v0.17.0
+
+// Update knative/serving to avoid CVE-2023-48713
+replace knative.dev/serving => knative.dev/serving v0.39.0
```
[the remark this answers is not in the document]
Comment (ckadner) [reply go.mod]: > It says that the vulnerability still present on 0.39.3

Where does it say that?

**Review by spolti — APPROVED** [review]

**Comment by ckadner** [comment]
Thanks @spolti for several rounds of reviews! 🙏🏻
